import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Product } from '../../../../libs/common/src/entity/products.entity';

@Injectable()
export class SeederService {
  constructor(
    @InjectRepository(Product)
    private readonly productRepository: Repository<Product>,
  ) {}

  async seed(): Promise<void> {
    const products = [
      {
        categoryName: 'Electronics',
        sku: 'ELEC-001',
        name: 'Smartphone',
        description: 'Latest model smartphone with high-end features',
        weight: 200,
        width: 75,
        length: 150,
        height: 8,
        image: 'smartphone.jpg',
        price: 500,
      },
      {
        categoryName: 'Electronics',
        sku: 'ELEC-002',
        name: 'Laptop',
        description: 'High-performance laptop for gaming and work',
        weight: 1500,
        width: 300,
        length: 400,
        height: 20,
        image: 'laptop.jpg',
        price: 1200,
      },
      {
        categoryName: 'Home Appliances',
        sku: 'HOME-001',
        name: 'Washing Machine',
        description: 'Front-load washing machine with energy efficiency',
        weight: 8000,
        width: 600,
        length: 600,
        height: 850,
        image: 'washing_machine.jpg',
        price: 600,
      },
      {
        categoryName: 'Furniture',
        sku: 'FURN-001',
        name: 'Sofa Set',
        description: 'Comfortable 3-piece sofa set for living rooms',
        weight: 25000,
        width: 2000,
        length: 800,
        height: 900,
        image: 'sofa_set.jpg',
        price: 900,
      },
      {
        categoryName: 'Furniture',
        sku: 'FURN-002',
        name: 'Dining Table',
        description: 'Wooden dining table with seating for 6',
        weight: 30000,
        width: 1500,
        length: 1200,
        height: 800,
        image: 'dining_table.jpg',
        price: 700,
      },
      {
        categoryName: 'Electronics',
        sku: 'ELEC-003',
        name: 'Smartwatch',
        description: 'Smartwatch with fitness tracking and notifications',
        weight: 50,
        width: 40,
        length: 40,
        height: 10,
        image: 'smartwatch.jpg',
        price: 200,
      },
      {
        categoryName: 'Electronics',
        sku: 'ELEC-004',
        name: 'Headphones',
        description: 'Noise-canceling headphones with high-quality sound',
        weight: 300,
        width: 150,
        length: 150,
        height: 50,
        image: 'headphones.jpg',
        price: 150,
      },
      {
        categoryName: 'Home Appliances',
        sku: 'HOME-002',
        name: 'Air Conditioner',
        description: 'Split air conditioner with energy-saving mode',
        weight: 9000,
        width: 1000,
        length: 300,
        height: 300,
        image: 'air_conditioner.jpg',
        price: 800,
      },
      {
        categoryName: 'Clothing',
        sku: 'CLOTH-001',
        name: "Men's T-Shirt",
        description: 'Cotton t-shirt available in various sizes and colors',
        weight: 200,
        width: 400,
        length: 600,
        height: 10,
        image: 'tshirt.jpg',
        price: 20,
      },
      {
        categoryName: 'Clothing',
        sku: 'CLOTH-002',
        name: 'Jeans',
        description: 'Comfortable jeans with a slim fit design',
        weight: 500,
        width: 800,
        length: 1000,
        height: 20,
        image: 'jeans.jpg',
        price: 50,
      },
      {
        categoryName: 'Beauty',
        sku: 'BEAUTY-001',
        name: 'Facial Cream',
        description: 'Moisturizing cream for face and neck',
        weight: 100,
        width: 50,
        length: 50,
        height: 50,
        image: 'facial_cream.jpg',
        price: 30,
      },
      {
        categoryName: 'Beauty',
        sku: 'BEAUTY-002',
        name: 'Shampoo',
        description: 'Herbal shampoo for healthy hair',
        weight: 300,
        width: 100,
        length: 100,
        height: 250,
        image: 'shampoo.jpg',
        price: 15,
      },
      {
        categoryName: 'Books',
        sku: 'BOOK-001',
        name: 'Programming Guide',
        description: 'Comprehensive guide to programming in JavaScript',
        weight: 500,
        width: 200,
        length: 250,
        height: 30,
        image: 'programming_guide.jpg',
        price: 40,
      },
      {
        categoryName: 'Books',
        sku: 'BOOK-002',
        name: 'Novel: The Great Adventure',
        description: 'Fiction novel with an exciting storyline',
        weight: 400,
        width: 150,
        length: 200,
        height: 20,
        image: 'novel.jpg',
        price: 20,
      },
      {
        categoryName: 'Sports',
        sku: 'SPORTS-001',
        name: 'Football',
        description: 'Standard size football for recreational play',
        weight: 500,
        width: 220,
        length: 220,
        height: 220,
        image: 'football.jpg',
        price: 25,
      },
      {
        categoryName: 'Sports',
        sku: 'SPORTS-002',
        name: 'Tennis Racket',
        description: 'High-quality tennis racket for professionals',
        weight: 350,
        width: 70,
        length: 700,
        height: 50,
        image: 'tennis_racket.jpg',
        price: 100,
      },
      {
        categoryName: 'Kitchen',
        sku: 'KITCHEN-001',
        name: 'Blender',
        description: 'Powerful blender for smoothies and shakes',
        weight: 1000,
        width: 200,
        length: 200,
        height: 400,
        image: 'blender.jpg',
        price: 120,
      },
      {
        categoryName: 'Kitchen',
        sku: 'KITCHEN-002',
        name: 'Microwave Oven',
        description: 'Microwave oven with various cooking presets',
        weight: 1500,
        width: 500,
        length: 400,
        height: 300,
        image: 'microwave_oven.jpg',
        price: 150,
      },
    ];

    await this.productRepository.save(products);
    console.log('Seeder: Product data seeded successfully');
  }
}
